// flow-typed signature: 2629fc59b073d0867fc8426cd5dd52f7
// flow-typed version: <<STUB>>/babel-traverse_v6.26.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-traverse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-traverse' {
  declare function visitor(path: Object): null;

  declare type Visitors = {
    [string]: visitor,
  };

  declare export default function method(ast: any, visitors: Visitors): any;
}
