// flow-typed signature: b6636e28fc4ae9133708858b24ebbbdc
// flow-typed version: <<STUB>>/babylon_v6.18.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babylon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babylon' {
  declare export function parse(input: string, options: Object): any;
}
