// flow-typed signature: c84dd45f8a92532240b50b7458b5ba33
// flow-typed version: <<STUB>>/pug-lexer_v4.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pug-lexer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pug-lexer' {
  declare export default function method(input: string): Array<Token>;
}
