version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/pug-uses-variables

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: yarn lint
      - run: yarn flow
      - run: yarn test --runInBand
