version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/pug-uses-variables

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run: yarn lint
      - run: yarn flow
      - run: yarn test --runInBand
